# Gunakan image Python resmi
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Salin semua file ke container
COPY . /app

# Instal dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Buka port untuk Panel
EXPOSE 7860

# Jalankan dashboard Panel
CMD ["panel", "serve", "dashboard_auto_mpg.py", "--address", "0.0.0.0", "--port", "7860", "--allow-websocket-origin=*"]